## 1. 출력 
- print() 함수 : 괄호안에 출력하고 싶은 것을 나열한다.


In [ ]:
print("Hello world")

Hello world


<font color='red'>Q1 한번 출력해보세요 </font>

In [ ]:
?????

## 2. 자료형과 문자열 
- 문자열(string) : 메일제목 , 메세지 내용 등 -> 예 ) "안녕하세요", "Hello World!"
- 숫자(number) : 물건의 가격, 학생의 성적 등 -> 예) 52, 235, 13.25
- 불(boolean) : 친구의 로그인 상태 등 -> 예 )True, False 

참조: 혼자 공부하는 파이썬

### 2.1 자료형 확인하기
- type()함수 사용

In [ ]:
print(type(23))
print(type(45.2))
print(type('가나다'))
print(type(False))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


<font color='red'>Q2 다양한 값들의 자료형을 확인해 봅니다. </font>

In [ ]:
?????

## 3. 산술연산자에 대하여 알아보겠습니다. 

- 더하기 기호는  + 입니다. 
- 빼기는 - 입니다. 
- 곱하기는 * 입니다. 
- 나누기를 하는 기호는 / 입니다.
- 거듭제곱은 **입니다.
- 나머지는 % 입니다.
- 몫은 // 입니다.  

아래에 여러분들이 수식을 사용해서 연산을 해보세요!<br>
간단한 예제를 아래와 같이 보여 드리겠습니다. <br>
셀을 생성 할 때는 위에 +코드를 눌러주세요<br>


In [ ]:
1+2 

3

In [ ]:
3 * 7

21

<font color='red'>Q3 사칙연산을 한번 해봅시다. </font>

In [ ]:
?????

## 4. 비교연산자 
- 같다 :  ==
- 같지않다 : !=
- 작다 : <
- 크다 : >
- 작거나 같다 : <=
- 크거나 같다 : >=

In [ ]:
print( 7 == 9 ) 
print (7 != 9 ) 
print (7 < 9 )
print (7 > 9)
print (7 <= 9)
print (7 >= 9)

<font color='red'>Q4 100과 -100의 대소를 비교해보세요 </font>

In [ ]:
?????

## 5. 문자연산자
### 5.1 문자연결연산자 
- 두 만자열을 연결해서 새로운 문자를 만들어 낸다. 
- 문자열은 무조건 문자열끼리 + 기호를 사용해서 연결한다. 
- 숫자라고 하더락도 문자열과 연산하려면 큰따옴표를 붙여 문자열로 인식시킨다.
  - 참조: 혼자서공부하는 파이썬

In [ ]:
print("안녕하세요"+ "반갑습니다.")

In [ ]:
print("안녕하세요" + 1)

TypeError: ignored

In [ ]:
print("안녕하세요" + "123")

안녕하세요123


### 5.2 문자열을 반복연산
- 문자열 *의로 반복이 가능하다. 

In [ ]:
print("안녕 " * 3)

안녕 안녕 안녕 


### 5.3 문자 선택 연산자(인덱싱): [ ]
- 내부의 문자하나를 선택하는 연산자
- 대괄호 [ ]안에 선택할 문자의 위치 지정 , 이 숫자를 인덱스(index)라고 부른다. 


In [ ]:
print("감사합니다."[0])
print("감사합니다."[1])
print("감사합니다."[2])
print("감사합니다."[3])
print("감사합니다."[4])
print("감사합니다."[5])

감
사
합
니
다
.


### 5.4 거꾸로 문자를 출력해 봅시다. 


In [ ]:
print("감사합니다."[-1])
print("감사합니다."[-2])
print("감사합니다."[-3])
print("감사합니다."[-4])
print("감사합니다."[-5])
print("감사합니다."[-6])

.
다
니
합
사
감


### 5.5 문자열 범위 섵택 연산자(슬라이싱): [ : ]
- 문자열의 특정 범위를 선택 할 때 사용하는 연산자

In [ ]:
print("서울시립대학교"[4:7])

대학교


In [ ]:
# 서울 시립대학교 에서 시립만 출력해 봅니다.(공백불포함) 
# 서울 이후의 모든 단어를(공백포함) 출력합니니다.
# 대학교 앞의 단어들을 모두 출력합니다. 

In [ ]:
print("서울 시립대학교"[3:5])
print("서울 시립대학교"[2:])
print("서울 시립대학교"[:-3])

시립
 시립대학교
서울 시립


### 5.6 문자열의 길이 구하기
- len()함수를 이용하여 구한다.

In [ ]:
print(len("인공지능학과"))

6


### 5.7 리스트(list)

지금까지 숫자, 문자열, 불 데이터 타입을 알아봤습니다. 
하나씩만 처리할 수 있었던 데이커를 묶어서 관리하면 편리한데 이렇게 하느것이 리스트(List) 타입입니다. 
- 리스트는 대괄호를 이용해서 만듭니다. ([ ])
- 대괄호 안에 올 수 있는 항목의 데이터 타입은 다양합니다. 
- 데이터는 입력한 순서대로 지정되며, 항목은 콤마(,)로 구분합니다. 
- 대괄호 내부에 넣는 자료를 요소라고 하고 영어로 element 라고 부릅니다. 


In [ ]:
# 리스트를 만들어 봅시다. 
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [ ]:
lst = [234,56,"안녕하세요", True, False]
lst
print(type(lst))

<class 'list'>


lst 리스트는 순서대로 0,1,2,3의 위치 정보를 갖고 있습니다. 
- lst[0]: 234
- lst[1]: 56
- lst[2]: "안녕하세요" 
- lst[3]: True
- lst[4]: False

[ ] 괄호안에 숫자를 인덱스라고 합니다.
문자열에서 배웠던 방법과 마찬가지로 대괄호 안에 음수를 넣어 뒤어서 부터 요소를 선택할 수 있습니다.


In [ ]:
#다양한 방법으로 문자들을 출력해 보세요.
lst[-1]

False

In [ ]:
lst[2]

'안녕하세요'

- 리스트 연산자 : 연결 (+), 반복(*), len()
- 리스트에 요소 추가하기 : append(뒤로 element를 추가), insert(중간에 element추가), extend(한꺼번에 여러 요소를 추가)
- 인덱스로 제거 하기: del, pop
- 값으로 제거하기 : remove()
- 모두제거 : clear()
- 리스트 내부에 있는지 확인하기 : in, notin

In [ ]:
#리스트 연산자 사용
lst_a =[1,2,3,4]
lst_b =[5,6,7,8]
# + 연산자
print(lst_a+lst_b)
 # * 연산자
print(lst_a * 4)
# len
print(len(lst_b))


[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
3


In [ ]:
#append() -> 리스트 명.append(element)
lst_a.append(8)

#insert() -> 리스트명.insert(위치, 요소)
lst_b.insert(3,10) # 이때 해당위치는 밀리게 됩니다. 

#extend()
lst_a.extend([7,8,9])

In [ ]:
lst_c =[1,2,3,4,5]
#del -> del 리스트명[index]
del lst_c[1]
print(lst_c)
#pop -> 리스트명.pop(인덱스)
lst_c.pop(2)
print(lst_c)

In [ ]:
lst_d = [1,2,3,4,5,6]
#remove -> 리스트.remove(값)
lst_d.remove(4)

#clear -> 리스트.clear()
lst_d.clear()

In [ ]:
#in
lst_e = [234,56,42,345,67]
234 in lst_e

#notin

56 not in lst_e
44 not in lst_e

True

<font color='red'>Q5 x=[100,200,300,400,500] 로 선언하고, indexing을 통해 300만 가져와봅시다!  </font>

In [ ]:
?????

### 6. 변수

- 변수(variable) : 숫자와 같은 자료(data)를 넣을 수 있는 상자
- 실제로 변수는 컴퓨터의 임시 저장공간(메모리)에 저장 된다. 
- 변수명과 등호, 등호와 data 사이의 공백은 무시된다. 
- 변수명으로 할 당 한 값을 출력가능 하다.
  - 참조: 데이터분석을 위한 파이썬 철저입문


In [ ]:
abc = 12340
print(abc)

12340


In [ ]:
# 변수를 가지고 연산을 해봅니다.
abc * 1/2

6170.0

### 6.1 변수를 만들 때 규칙
- 변수명은 문자, 숫자, 밑줄 기호(_)를 이용해 만든다. 
- 숫자로 시작하는 변수명을 만들 수 없다. 
- 대소문자를 구분한다. 
- 공백을 포함 할 수 없다. 
- 밑줄 이외의 기호는 변수에 사용할 수 없다. 
- 예약어(Reserved word)는 변수명으로 이용할 수 없다.
- 아래의 코드에서 예약어를 확인 할 수 있다.
  - 참조: 혼자공부하는 파이썬

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


### 6.2 사용자 입력 input()
- 프롬프트에 글자를 입력하고 그 입력을 읽어 활용하는 경우에 활용가능

In [ ]:
input("이름을 입력하세요")

input 함수의 입력 자료를 출력해 보세요.

In [ ]:
birth = input("생일을 입력하세요.")
print(type(birth))

<font color='red'>Q6 본인 이름의 이니셜로 변수명을 만들고, 거기에 숫자 100을 선언해보세요.</font>

In [ ]:
?????

## 7. 모듈(Module)
- 파이썬에서는 코드가 저장된 파일을 모듈(Module)이라고 합니다. 
- 상수, 변수, 함수, 클래스를 포함하는 코드가 저장된 파일입니다. 
- 
- 다른모듈에서도 불러서 실행 할 수도 있고 파이썬 콘솔이나 주피터 노트북에서 불러서 실행할 수 도 있습니다.
- 일단 우리는 모듈을 생성하기 보다 미리 생성된 모듈을 많이 사용하게 되는데, 그 방법에 대하여 알아봅시다. 


#### 7.1 모듈 불러오기
- import 모듈명
    무언가를 계속 입력하는 것이 귀찮다고 느껴질 때 사용하는 from을 사용합니다. 
- from 모듈명 import 변수명
- from 모듈명 import 함수명
- from 모듈명 import 클래스명
- from 모듈명 import *  : 모듈내 모든 변수, 함수, 클래스를 불러올 떄
- import 모듈명 as 별칭 : 모듈명이 길어서 입력하기 번거러울 떄 사용


In [ ]:
# math 모듈 불러오기
import math

#### 7.2 math 모듈
- sin(x) : 사인값을 구합니다.
- cos(x) : 코사인값을 구합니다. 
- tan(x) : 탄젠트 값을 구합니다. 
- log(x[,base]) fhrmrkqtdmf rngkqslek. 
- ceil(x) : 올림합니다. 
- floor(x): 내림합니다. 

In [ ]:
# 사용해 봅시다.
math.sin(1)
# import 실행을 반드시 해야 사용이 가능합니다!
# math를 계속 쓰는게 귀찮으면 
from math import sin, cos, tan, floor, ceil
# 형식으로 부를 수 있습니다. 
# 그러면 math.sin() 이아니라.

sin(1) #으로 사용이 가능합니다. 


0.8414709848078965

모듈에 대하여 궁금하다면 python 공식 doc을 읽어보는 것을 추천합니다. <br>
https:// docs.python.org/3/library/index.html

#### 7.3 자주 사용하는 표준 모듈
- random : 랜덤한 값을 생성 할 때 사용
- os  : 운영체제와 관련된 기능 가진 모듈 
- sys : 시스템과 관련된 정보를 가지고 있는 모듈
- datetime : 날짜와 시간 관련된 모듈,  

<font color='red'>Q7 pandas를 한번 import 해보세요 </font>

In [15]:
?????

### 8. 배열을 효과적으로 다루는 NumPy
- NumPy는 파이썬의 내장 모듈이 아님으로 별로로 설치 해야 합니다. 
- colab에서 는 기본적으로 설치가 되어 있습니다. 

#### 8.1 배열생성하기

In [4]:
# 모듈 호출
import numpy as np

#### 8.1.1- 시퀀스 테이터로 부터 배열 생성 하는 방법
  - array_obj=np.array(seq_data)
데이터 들의 타입을 잘 확인해 보자!

In [ ]:
data1 = [1, 2, 3, 4, 5]
a = np.array(data1)
a

dtype('int64')

In [ ]:
data2=[0.1, 3, 7, 15, 0.7]
a2=np.array(data2)
a2

array([ 0.1,  3. ,  7. , 15. ,  0.7])

In [ ]:
np.array([2,4,0.7,2.5])

array([2. , 4. , 0.7, 2.5])

In [ ]:
np.array([[2,3,4],[4,5,6],[6,7,8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# 위의  배열(a와 12의)의 타입을 확인해 보세요!
print(type(a))
print(type(a2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#위의 배열의 속성을 확인 하세요!
print(a.dtype)
print(a2.dtype)

int64
float64


#### 8.1.2- 범위를 지정해서 배열생성
  - array_obj = np.arrange([start],stop[ , step])
  - start 부터 시작해서 stip전까지 step만큼 계속 더해 NumPy의 배열을 생성.
  - step 1인경우에는 start도 생략하고 numpy.arange(stop)처럼 사용가능
  - arange 를 쓸 때 어디 까지 출력이 되는지 잘 살펴보자.
  - arange()를 이용해 생성한 1차원 배열에  reshape(m,n)을 추가하면 m x n 형태의 2차원 **배열(행렬)**로 변경이 가능   
  - zeros(n) : zero값으로 n개
  - zeros((n,m)) : 2차원 배열을 n 행 m열 로 생성

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- 주의 할 점은 arange() 로 생성되는 배열의 원소 개수와 reshape(m,n) 의 개수는 같아야 한다!!!

- NumPy 배열의 형태를 알기 위해서는 ndarrqy.shape를 실행한다. 

In [ ]:
s = np.arange(15).reshape(3,5)
s.shape

(3, 5)

In [ ]:
np.linspace(0, np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 8.2 난수 배열 생성
- rand() 0~1 까지의 값
- randint() int값만


In [ ]:
np.random.rand(3,4)

array([[0.69575489, 0.01237098, 0.46385756, 0.44028007],
       [0.59489922, 0.96822509, 0.23846117, 0.59989225],
       [0.56883222, 0.29068118, 0.12753432, 0.27207479]])

In [ ]:
np.random.rand()

0.8497134089256334

In [ ]:
np.random.rand(2,3,4)

array([[[0.67145471, 0.55223401, 0.14699538, 0.41505207],
        [0.04240118, 0.38494175, 0.95119745, 0.65034109],
        [0.49953339, 0.42406843, 0.8368027 , 0.87887591]],

       [[0.7133873 , 0.31743237, 0.99773034, 0.05913768],
        [0.96720836, 0.69437487, 0.99063445, 0.59538718],
        [0.80157037, 0.70625866, 0.24562482, 0.93603805]]])

In [ ]:
np.random.randint(10, size=(3,4))

array([[9, 6, 1, 3],
       [4, 5, 9, 7],
       [1, 2, 3, 5]])

In [ ]:
np.random.randint(1,30)

16

#### 8.3 배열의 연산

1. arr1과 arr2를 선언하세요. array안에 요소는 각각 4개로 선언합니다. 
2. 배열의 더하기를 해보세요
3. 배열간의 빼기를 해보세요.
4. arr2에 3을 곱한 값을 구하세요.
5. arr2의 제곱을 구하세요.
6. arr1과 arr2의 곱을 구하세요. 
7. arr1을 arr2로 나누어 지나요? 그렇다면 그 값은 어떻게 될까요?
8. arr1은 12보다 큰 값이 몇 개 있습니까?

In [ ]:
arr1= np.array([12,13,14,15])
arr2= np.array([2,3,4,5])

In [ ]:
arr1 + arr2

array([14, 16, 18, 20])

In [ ]:
arr1-arr2

array([10, 10, 10, 10])

In [ ]:
arr2 *3

array([ 6,  9, 12, 15])

In [ ]:
arr2**2

array([ 4,  9, 16, 25])

In [ ]:
arr1 *arr2

array([24, 39, 56, 75])

In [ ]:
arr1/arr2

array([6.        , 4.33333333, 3.5       , 3.        ])

In [ ]:
arr1>12

array([False,  True,  True,  True])

#### 8.4 통계를 위한 연산
- Numpy에서는  통계 에 활용되는 메소드들이 있다. 
- 배열의 합: sum()
- 평균 : mean()
- 표준편차 : std()
- 분산 : var()
- 최솟값 : min()
- 최대값 : max()
- 누적합 : cumsum()
- 누적 곱 : cumprod()

In [ ]:
arr3 = np.arange(6)
arr3

array([0, 1, 2, 3, 4, 5])

In [ ]:
[arr3.sum(), arr3.mean()]

[15, 2.5]

In [ ]:
[arr3.std(), arr3.var()]

[1.707825127659933, 2.9166666666666665]

In [ ]:
[arr3.min(), arr3.max()]

[0, 5]

In [ ]:
[arr3.cumsum(), arr3.cumprod()]

[array([ 0,  1,  3,  6, 10, 15]), array([0, 0, 0, 0, 0, 0])]

#### 8.5 행렬 연산
- 행렬곱(matrix droduct) : A.dot(B) 혹은 np.dot(A,B)
- 전치행렬(transpose matrix) : A.transpose() 혹은 np.transpose(A)
- 역행렬(invers matrix) : np.linalg.inv(A)
- 행렬식(determinant) : np.linalg.det(A)
- Norm : np.linalg.norm(v)

In [5]:
#A = np.array([0,1,2,3]).reshape(2,2)
A = np.array([[0,1],[2,3]])
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3,2,1,0]).reshape(2,2)
B

array([[3, 2],
       [1, 0]])

In [ ]:
A.dot(B)

array([[1, 0],
       [9, 4]])

In [ ]:
np.dot(A,B)

array([[1, 0],
       [9, 4]])

In [ ]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [ ]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
np.linalg.inv(B)

array([[ 0. ,  1. ],
       [ 0.5, -1.5]])

In [ ]:
np.linalg.det(A)

-2.0

In [ ]:
C = np.array([1,2,3,4,5,6]).reshape(3,2)
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A.dot(C) # 행 열이 일치 하지 않으면 행렬의 곱을 진행 할 수 없습니다. 

ValueError: ignored

In [12]:
v = [3,4]
l1_norm = np.linalg.norm(v,ord=1)
l2_norm = np.linalg.norm(v,ord=2)
linf_norm = np.linalg.norm(v,ord=np.inf)

print(l1_norm,l2_norm,linf_norm)

7.0 5.0 4.0


<font color='red'>Q8 x = [$1/\sqrt{2}$,$1/\sqrt{2}$]로 선언하고, x의 L2norm을 구하세요. </font>

In [ ]:
?????