## QuantEcon Study Material
> Source : https://datascience.quantecon.org/scientific/index.html

#### TL;DR 
Break down fundamental knowledge and skills of scientific computing methodology of Python

----

## Scientific Computing
This section discusses several key aspects of scientific computing **that enable modern economics, data science, and statistics.**

As the size of our data and the complexity of our models have increased (and continue doing so), we have become more reliant on computers to perform computations that we simply cannot do by hand.

In this section, we will cover

- Python’s main numerical library **numpy and how to work with its array type.**

- A basic introduction to **visualizing data with matplotlib.**

- A refresher on some **key linear algebra concepts.**

- A review of **basic probability concepts and how to use simulation** in learning economics.

- Using a computer to perform **optimization.**

----

# Introduction to Numpy

## Outcomes
- Understand basics about numpy arrays
- Index into multi-dimensional arrays
- Use universal functions/broadcasting to do element-wise operations on arrays

The foundational library that helps us perform these computations is known as numpy (numerical Python).

Numpy's core contribution is a new data-type called an **"array"**

An array is similar to a list, but numpy imposes some additional restrictions on how the data inside is organized.

These restrictions allow numpy to 

- 1. Be more efficient in performing mathematical and scientific computations.
- 2. Expose functions that allow numpy to do the necessary linear algebra for machine learning and statistics.

In [1]:
import numpy as np

### What is an Array ?

An array is a multi-dimensional grid of values.

What does this mean? It is easier to demonstrate than to explain.

In this block of code, we build a 1-dimensional array

In [2]:
x_1d = np.array([1,2,3]) # one-dimensional array
print(x_1d)

[1 2 3]


You can think of a 1-dimensional array as a list of numbers

In [3]:
print(x_1d[0])
print(x_1d[0:2])

1
[1 2]


Note that the range of indices does not include the end-point, that is

In [4]:
print(x_1d[0:3] == x_1d[:])
print(x_1d[0:2]) # 맨 마지막 index 제외하고 출력하는 것, 즉 1번째 까지

[ True  True  True]
[1 2]


Next, we define a 2-dimensional array **(a matrix)**

In [5]:
x_2d = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]
                ])
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Notice that the data is no longer represented as **something flat, but rather, as three rows and three columns of numbers**.

The first question that you might ask yourself is: "how do iI accss the values in this array?"

You access each element by specifying a row first and then a column. For example, if we wanted to access the 6, we would ask for the (1,2) element.

In [6]:
print(x_2d[1,2])
print(x_2d[0,1]) #list indexing과 동일하게 실제 인덱스보다 -1로 처리

6
2


To get the first, and then second rows...

In [7]:
print(x_2d[0:2,])

[[1 2 3]
 [4 5 6]]


In [8]:
print(x_2d[0,:])
print(x_2d[1,:])

[1 2 3]
[4 5 6]


or the columns...

In [9]:
print(x_2d[:, 0]) # 1번째 컬럼
print(x_2d[:, 1]) # 2번째 컬럼

[1 4 7]
[2 5 8]


This continues to generalize, since numpy gives us as many dimensions as we want in an array.

For example, we build a 3-dimensional array below.

In [10]:
x_3d_list = [[[1,2,3], [4,5,6]],    
             [[10,20,30], [40,50,60]]
            ]

x_3d = np.array(x_3d_list)

In [11]:
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


### Array indexing

Now that there are multiple dimensions, indexing might feel somewhat non-obvious.

do the rows or columns come first? In higher dimensions, what is the order of the index?

Notice that the array is built using a list of lists (you could also use tuples).

Indexing into the array will correspond to choosing elements from each list.

First, notice that the **dimensions give two stacked matrices**, which we can access with

In [12]:
print(x_3d[0]) # 3차원에서의 1행을 뽑아내면 행렬 하나가 나옴
print(x_3d[1]) # 마찬가지

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [13]:
print(x_3d[0, :, :])
print(x_3d[0])
# 똑같은 결과

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Let's work thru another example to further clarify this concept with our 3-dimensional array. Our goal will be to find the index that retrieves the `4` out of `x_3d`

Recall that when we created x_3d, we used the list `[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]`

In [14]:
print(f"The 0 element is {x_3d[0]}") # 행렬 1개
print(f"The 1 element is {x_3d[1]}") # 행렬 1개

The 0 element is [[1 2 3]
 [4 5 6]]
The 1 element is [[10 20 30]
 [40 50 60]]


In [15]:
print(f"The 0 element of the 0 element is {x_3d[0][0]}") # 행렬 1개 중 첫번째 행

The 0 element of the 0 element is [1 2 3]


In [16]:
print(f"The 1 element of the 0 element is {x_3d[0][1]}") # 행렬 1개 중 2번째 행

The 1 element of the 0 element is [4 5 6]


In [17]:
print(f"The 0 element of 1 element of the 0 element is {x_3d[0][1][0]}") # 행렬 1개 중 2번째 행의 1번째 원소

The 0 element of 1 element of the 0 element is 4


In [18]:
print(x_3d[0, 1, 0])
# 3d array가 갖고있는 첫번째 행렬의 두번째 행의 첫번째 원소

4


### Array Functionality

#### Array Properties
All numpy arrays have various useful properties. 

Properties are similar to methods in that they're accessed through the "dot noation." However, they aren't a function, so we don't need parentheses.

The two most frequently used properties are `shape` and `dtype`.

`shape` tells us how many elements are in each array dimension.

`dtype` tells us the types of an array's elements.

Let's do some examples to see these properties in action.

In [19]:
x = np.array([[1,2,3], [4,5,6]])
print(x.shape)
print(x.dtype)

(2, 3)
int64


We'll use this to practice unpacking a tuple, like x.shape, directly into varibles.

In [20]:
rows, columns = x.shape #tuble을 변수로 바인딩하는 방법
print(f"rows={rows}, columns={columns}")

rows=2, columns=3


In [21]:
x = np.array([True, False, True])

print(x.shape)
print(x.dtype)

(3,)
bool


Note that in the above, the `(3,)` represents a tuple of length 1, **distinct from a scalar integer 3.**

In [22]:
x = np.array([
    [[1.0, 2.0], 
     [3.0, 4.0], 
     [5.0, 6.0]],
    [[7.0, 8.0], 
     [9.0, 10.0], 
     [11.0, 12.0]]
])

# 3*2 행렬 2개 짜리 stacked 3d array <=> (2,3,2)

print(x.shape)
print(x.dtype)

(2, 3, 2)
float64


### Creating Arrays

It's usually **impractical to define arrays by hand** as we have done so far.

We'll often need to create an array with default values and then fill with other values. 

We can create arrays with the functions `np.zeros` and `np.ones`.

Both functions **take a tuple that denotes the shape of an array** and creates an array filled with 0s or 1s repectively.

In [24]:
sizes = (2,3,4) # 3*4짜리 행렬 2개 stack

x = np.zeros(sizes) #tuple을 인자로 받아서 그대로 사용
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
y = np.ones(3)
y

array([1., 1., 1.])

In [34]:
z = np.eye(2)
z # 2*2 항등 행렬 생성

array([[1., 0.],
       [0., 1.]])

### Broadcasting Operations

Two types of operations that will be useful for arrays of any dimensions are:

* 1. Operations between an array and a single number.
* 2. Operations bewteen two arrays of the same shape.

When we perform operations on an array by using a single number, we simply apply that operation to **every element of the array.** (Element-wise operation)

In [40]:
x = np.ones((2,2))
print("x = ", x)
print("x+2 = ", 2+x)
print("2*x = ", 2*x)
print("x/2 = ", x/2)

x =  [[1. 1.]
 [1. 1.]]
x+2 =  [[3. 3.]
 [3. 3.]]
2*x =  [[2. 2.]
 [2. 2.]]
x/2 =  [[0.5 0.5]
 [0.5 0.5]]


Operations between two arrays of the same size, in this case (2, 2), simply apply the operation element-wise between the arrays.

In [47]:
x = np.array([[1.0, 2.0], 
              [3.0, 4.0]])
y = np.ones((2,2))

print("x+y=", x+y) # 2*2 행렬의 덧셈 연산
print("----"*5)
print("(elementwise) x*y = ", x*y) # # 2*2 행렬의 원소곱 (element-wise operation)

x+y= [[2. 3.]
 [4. 5.]]
--------------------
(elementwise) x*y =  [[1. 2.]
 [3. 4.]]


## Universal Functions

We will often need to transform data by applying a function to every element of an array.

Numpy has good support for these operations, called *universal functions* or ufuncs for short.

The numpy documentation has a list of all available ufuncs. (https://docs.scipy.org/doc/numpy/reference/ufuncs.html?highlight=ufunc#available-ufuncs)

> You should think of operations between a single number and an array, as we just saw, as a ufunc.

Below, we will create an array that contains 10 points between 0 and 25.

In [51]:
# This is similar to range 
# but spits out 50 evenly spaced points from 0.5 to 25

x = np.linspace(0.5, 25, 10) # 0.5부터 25까지 동일 간격으로 10개 데이터 출력
x

array([ 0.5       ,  3.22222222,  5.94444444,  8.66666667, 11.38888889,
       14.11111111, 16.83333333, 19.55555556, 22.27777778, 25.        ])

We will experiment with some ufuncs below:

In [52]:
# applies the sin function to each element of x 
np.sin(x)

array([ 0.47942554, -0.08054223, -0.33229977,  0.68755122, -0.92364381,
        0.99966057, -0.9024271 ,  0.64879484, -0.28272056, -0.13235175])

Of course, we could do the same thing with a comprehension, but the code would be both less readable and less efficient.

In [55]:
np.array([np.sin(xval) for xval in x])

array([ 0.47942554, -0.08054223, -0.33229977,  0.68755122, -0.92364381,
        0.99966057, -0.9024271 ,  0.64879484, -0.28272056, -0.13235175])

You can use the inspector or the docstrings with `np.<TAB>` to see other available functions, such as

In [56]:
np.log(x)

array([-0.69314718,  1.17007125,  1.78245708,  2.15948425,  2.43263822,
        2.64696251,  2.82336105,  2.97325942,  3.10358967,  3.21887582])

A benefit of using the numpy arrays is that numpy has succinct code for combining vectorized operations.

In [58]:
# calculate log(z) * z elementwise

z = np.array([1,2,3])

np.log(z) * z

array([0.        , 1.38629436, 3.29583687])

## Other Useful Array Operations

We have barely scratched the surface of what is possible using numpy arrays.

We hope you will experiment with other functions from numpy and see how they work. 

Below, we demonstrate a few more array operations that we find most useful-just to give you an idea of what else you might find.

When you're attempting to do **an operation that you feel should be common**, the numpy library probably has it.

In [59]:
x = np.linspace(0,25,10) #0부터 25까지 간격 동일하게 10개 뽑아줘

In [64]:
print(x)
print("----")
print(f"length of array x is {len(x)}")

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
----
length of array x is 10


In [65]:
print(f"mean of array x is {np.mean(x)}")

mean of array x is 12.5


In [66]:
print(f"standard deviation of array x is {np.std(x)}")

standard deviation of array x is 7.9785592313028175


etc...

In [67]:
# 총 10개의 원소를 다른 shape으로 바꿔보자
np.reshape(x, (5,2))

array([[ 0.        ,  2.77777778],
       [ 5.55555556,  8.33333333],
       [11.11111111, 13.88888889],
       [16.66666667, 19.44444444],
       [22.22222222, 25.        ]])

Finally, `np.vectorize` can be conveniently used with numpy broadcasting and any functions

In [72]:
np.random.seed(42)
x = np.random.rand(10)
print(x)

def f(val):
    if val < 0.3: #scalar 기준으로 함수 정의했으므로 스칼라에 대해서는 오류 X
        return "low"
    else:
        return "high"
    
print(f(0.1)) #scalar, no problem
print(f(x)) # array, fails since f() is scalar

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
low


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
f_vec = np.vectorize(f)

print(f_vec(x))

['high' 'high' 'high' 'high' 'low' 'low' 'low' 'high' 'high' 'high']


Caution: `np.vectorize` is convenient for numpy broadcasting with any function but **is not intended to be high performance.**

When speed matters, directly write a f function to work on arrays.

## Exercise) Bond Pricing

\begin{split}
\begin{align*}
    P &= \left(\sum_{n=1}^N \frac{C}{(i+1)^n}\right) + \frac{M}{(1+i)^N} \\
      &= C \left(\frac{1 - (1+i)^{-N}}{i} \right) + M(1+i)^{-N}
\end{align*}
\end{split}

In the code cell below, we have defined variables for `i`, `M` and `C`.

You have two tasks:

* Define a numpy array `N` that contains all maturities between 1 and 10
> Hint : look at the `np.arange` function.
* Using the equation above, determine the bond prices of all maturity levels in your array.